version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
      MYSQL_DATABASE: buysell
    volumes:
      - /datadir:/var/lib/mysql
    restart: always
volumes:
  mysql_db:
    driver: local
